### ISSUE TITLE
Enabling the extension doesn't change anything (by default)

### ISSUE THREAD

**Issue by rcoopr** [mguellsegarra/highlight-on-copy#1]
Looks like a cool extension. I enabled it, found it had no effect so took a look at the code. Correct me if I'm wrong, but don't users need to define a keybinding to enable this? I did make it work via the following process in VS Code:

- Open keyboard shortcuts
- Search for `highlightOnCopy.run`
- Add shortcut (ctrl+c or cmd+c)
- Change `when` clause to `editorTextFocus`

I think the extension can contribute a keyboard shortcut by adding this to the `contributes` field in the `package.json`:

```json
{
    ...,
    "contributes": {
        ...,
        "keybindings": [
            {
                "command": "highlightOnCopy.run",
                "key": "ctrl+c",
                "mac": "cmd+c",
                "when": "editorTextFocus"
            }
        ]
    }
}
```

**Comment by mguellsegarra** [comment]
Hey @rcoopr 

> but don't users need to define a keybinding to enable this? 

Yes, you are absolutely right. In the current version, users are required to manually configure a keybinding. Both the README and the VSCode Marketplace extension description detail the process as you've described. I acknowledge that many users may not consult these resources (like you 😜), so I will incorporate a default keybinding directly into the extension to enhance usability.

Should be available in the next version.

Thanks!
