### ISSUE TITLE
Feature suggestion: Adapt to current theme

### ISSUE THREAD

**Issue by el-veee** [mguellsegarra/highlight-on-copy#11]
Would love for the highlight colour to adapt to the current VS Code theme.

Thanks for the great extension!

**Comment by mguellsegarra** [comment]
Hey @el-veee , you can already customize the colors in your settings.json, take a look at the documentation in the [README](https://github.com/mguellsegarra/highlight-on-copy)

Thanks for your support

**Comment by el-veee** [comment]
I more meant the colour automatically changes when the theme changes
