### ISSUE TITLE
Allow VS Code < 1.88

### ISSUE THREAD

**Issue by weleo** [mguellsegarra/highlight-on-copy#8]
The extension works on VS Code 1.86, but I had trouble installing due to the requirement of version 1.88. This issue was resolved by manually changing the required version in the extension manifest.

Keep in mind that some versions of VS Code or company-managed IDEs may be one or two updates behind. If the latest version is not necessary for the extension to run, it may be beneficial to allow for some flexibility.

Overall, this is a great idea, and the visual feedback it provides is appreciated.

**Comment by mguellsegarra** [comment]
Totally agree! Modified the minimum vscode version and should be available in the next update! Many thanks!
